### ISSUE TITLE
Directed interaction should be turned into "regulates" edge

### ISSUE THREAD

**Issue by cthoyt** [PathwayMerger/PathMe#17]
should be `p(HGNC:GRB2) regulates p(HGNC:PTPN11)`

<img width="1265" alt="screenshot 2019-01-23 14 26 14" src="https://user-images.githubusercontent.com/5069736/51609639-e732fd00-1f1a-11e9-9b6d-7319ef1a816b.png">

**Comment by cthoyt** [comment]
Maybe we should also update the display to be dotted with an arrow and cross through it.

**Comment by ddomingof** [comment]
@jmarinllao add case for "DirectInteraction" and convert it into "regulates" relationship in BEL
