### ISSUE TITLE
Improve documentation for xml_complexes_to_bel

### ISSUE THREAD

**Issue by cthoyt** [PathwayMerger/PathMe#3]
Currently, this function is causing a failure in the tests because something that shouldn't be hashed is getting stuck as a key in a dictionary during the call to this function. It's not clear what's supposed to be going in to this function from the documents though... It would be helpful to improve the documentation with type hints that go deeper than just `dict` - what are the keys and values supposed to be for `node_dict` and `complex_ids`?

https://github.com/ComPath/PathMe/blob/d3ff85f51c96279ac5b296709ad55adbd66d452c/src/pathme/kegg/convert_to_bel.py#L121-L147

**Comment by ddomingof** [comment]
Example: 
     :param dict node_dict:  kegg_id to BEL node dictionary

**Comment by cthoyt** [comment]
@ddomingof no, that's not far enough. It needs to have the key and values explicit!

:param dict[str,BaseEntity] node_dict: kegg_id to BEL node dictionary
